"""
code_generator.py
Генератор артефактів: VHDL файли з шаблонів,
C++ обгортки (pybind11 / header-only), команди бітстріму.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path
from string import Template
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from spartan7_optimizer import ModuleSpec, Connection, ModuleKind

log = logging.getLogger(__name__)

# ──────────────────────────────────────────────
#  VHDL шаблони (inline)
# ──────────────────────────────────────────────
_MUX_TEMPLATE = """\
-- AUTO-GENERATED by spartan7_optimizer  DO NOT EDIT MANUALLY
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity ${entity_name} is
  generic (
    WIDTH  : positive := ${width};
    INPUTS : positive := ${inputs}
  );
  port (
    sel    : in  std_logic_vector(${sel_bits}-1 downto 0);
    data_i : in  std_logic_vector(INPUTS*WIDTH-1 downto 0);
    data_o : out std_logic_vector(WIDTH-1 downto 0)
  );
end entity;

architecture rtl of ${entity_name} is
begin
  process(sel, data_i)
    variable idx : integer range 0 to INPUTS-1;
  begin
    idx    := to_integer(unsigned(sel));
    data_o <= data_i((idx+1)*WIDTH-1 downto idx*WIDTH);
  end process;
end architecture;
"""

_DEMUX_TEMPLATE = """\
-- AUTO-GENERATED by spartan7_optimizer  DO NOT EDIT MANUALLY
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity ${entity_name} is
  generic (
    WIDTH   : positive := ${width};
    OUTPUTS : positive := ${outputs}
  );
  port (
    sel    : in  std_logic_vector(${sel_bits}-1 downto 0);
    data_i : in  std_logic_vector(WIDTH-1 downto 0);
    data_o : out std_logic_vector(OUTPUTS*WIDTH-1 downto 0)
  );
end entity;

architecture rtl of ${entity_name} is
begin
  process(sel, data_i)
    variable idx : integer range 0 to OUTPUTS-1;
  begin
    data_o <= (others => '0');
    idx    := to_integer(unsigned(sel));
    data_o((idx+1)*WIDTH-1 downto idx*WIDTH) <= data_i;
  end process;
end architecture;
"""

_FIFO_TEMPLATE = """\
-- AUTO-GENERATED by spartan7_optimizer  DO NOT EDIT MANUALLY
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity ${entity_name} is
  generic (
    DEPTH : positive := ${depth};
    WIDTH : positive := ${width}
  );
  port (
    clk     : in  std_logic;
    rst     : in  std_logic;
    wr_en   : in  std_logic;
    rd_en   : in  std_logic;
    din     : in  std_logic_vector(WIDTH-1 downto 0);
    dout    : out std_logic_vector(WIDTH-1 downto 0);
    full    : out std_logic;
    empty   : out std_logic;
    count   : out std_logic_vector(${addr_bits} downto 0)
  );
end entity;

architecture rtl of ${entity_name} is
  type mem_t is array(0 to DEPTH-1) of std_logic_vector(WIDTH-1 downto 0);
  signal mem                      : mem_t := (others => (others => '0'));
  signal wr_ptr, rd_ptr           : unsigned(${addr_bits} downto 0) := (others => '0');
  signal item_count               : unsigned(${addr_bits} downto 0) := (others => '0');
begin
  count <= std_logic_vector(item_count);
  full  <= '1' when item_count = DEPTH else '0';
  empty <= '1' when item_count = 0    else '0';

  process(clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        wr_ptr <= (others => '0');
        rd_ptr <= (others => '0');
        item_count <= (others => '0');
      else
        if wr_en = '1' and item_count < DEPTH then
          mem(to_integer(wr_ptr(${addr_bits}-1 downto 0))) <= din;
          wr_ptr <= wr_ptr + 1;
          item_count <= item_count + 1;
        end if;
        if rd_en = '1' and item_count > 0 then
          dout   <= mem(to_integer(rd_ptr(${addr_bits}-1 downto 0)));
          rd_ptr <= rd_ptr + 1;
          item_count <= item_count - 1;
        end if;
      end if;
    end if;
  end process;
end architecture;
"""

_TOP_WRAPPER_TEMPLATE = """\
-- AUTO-GENERATED top-level wrapper
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity top_wrapper is
  port (
    clk  : in  std_logic;
    rst  : in  std_logic
    -- USER PORTS GENERATED HERE
${port_list}
  );
end entity;

architecture structural of top_wrapper is
${component_decls}
begin
${component_instances}
${connections_vhdl}
end architecture;
"""

# ──────────────────────────────────────────────
#  CodeGenerator
# ──────────────────────────────────────────────
class CodeGenerator:
    """Генерує VHDL-артефакти і C++ заголовки."""

    def __init__(self, work_dir: str = "build"):
        self.work_dir = Path(work_dir)
        self.vhdl_dir = self.work_dir / "generated_vhdl"
        self.vhdl_dir.mkdir(parents=True, exist_ok=True)

    # ── VHDL генерація ─────────────────────
    def generate_vhdl(
        self,
        modules: list["ModuleSpec"],
        connections: list["Connection"],
        config: dict[str, str],        # ім'я модуля → обраний стиль
        device_id: str,
    ) -> list[str]:
        """
        Генерує .vhd файл для кожного модуля + top_wrapper.
        Повертає список шляхів до згенерованих файлів.
        """
        from spartan7_optimizer import ModuleKind
        files: list[str] = []

        for m in modules:
            style = config.get(m.name, "LUT")
            path  = self._generate_module_vhdl(m, style)
            if path:
                files.append(path)

        # Top wrapper
        top_path = self._generate_top_wrapper(modules, connections)
        files.append(top_path)

        log.info("Згенеровано %d VHDL файлів у %s", len(files), self.vhdl_dir)
        return files

    def _generate_module_vhdl(self, m: "ModuleSpec", style: str) -> str:
        from spartan7_optimizer import ModuleKind
        import math

        entity = self._safe_name(m.name)
        out_path = str(self.vhdl_dir / f"{entity}.vhd")

        if m.kind == ModuleKind.MUX:
            sel_bits = max(1, int(math.ceil(math.log2(max(m.inputs, 2)))))
            vhdl = _MUX_TEMPLATE
            vhdl = vhdl.replace("${entity_name}", entity)
            vhdl = vhdl.replace("${width}",    str(m.data_width))
            vhdl = vhdl.replace("${inputs}",   str(m.inputs))
            vhdl = vhdl.replace("${sel_bits}", str(sel_bits))

        elif m.kind == ModuleKind.DEMUX:
            sel_bits = max(1, int(math.ceil(math.log2(max(m.inputs, 2)))))
            vhdl = _DEMUX_TEMPLATE
            vhdl = vhdl.replace("${entity_name}", entity)
            vhdl = vhdl.replace("${width}",    str(m.data_width))
            vhdl = vhdl.replace("${outputs}",  str(m.inputs))
            vhdl = vhdl.replace("${sel_bits}", str(sel_bits))

        elif m.kind in (ModuleKind.RAM, ModuleKind.FIFO):
            addr_bits = max(1, int(math.ceil(math.log2(max(m.depth, 2)))))
            vhdl = _FIFO_TEMPLATE
            vhdl = vhdl.replace("${entity_name}", entity)
            vhdl = vhdl.replace("${depth}",     str(m.depth))
            vhdl = vhdl.replace("${width}",     str(m.data_width))
            vhdl = vhdl.replace("${addr_bits}", str(addr_bits))

        else:
            # DSP/ALU/MUL — просто заглушка entity
            vhdl = (
                f"-- AUTO-GENERATED placeholder for {m.kind.value}\n"
                f"-- Implement using DSP48E1 primitives\n"
                f"library IEEE;\nuse IEEE.STD_LOGIC_1164.ALL;\n"
                f"entity {entity} is port (\n"
                f"  clk : in std_logic\n);\nend entity;\n"
                f"architecture rtl of {entity} is\nbegin\nend architecture;\n"
            )

        Path(out_path).write_text(vhdl, encoding="utf-8")
        return out_path

    def _generate_top_wrapper(
        self,
        modules: list["ModuleSpec"],
        connections: list["Connection"],
    ) -> str:

        port_lines: list[str] = []
        comp_decls: list[str] = []
        comp_insts: list[str] = []
        conn_lines: list[str] = []

        for m in modules:
            entity = self._safe_name(m.name)
            port_lines.append(f"    -- ports for {entity} are internal")
            comp_decls.append(
                f"  component {entity} is port (clk : in std_logic); end component;"
            )
            comp_insts.append(
                f"  {entity}_inst : entity work.{entity}\n"
                f"    port map (clk => clk);"
            )

        for c in connections:
            conn_lines.append(
                f"  -- {c.src_name}.{c.src_port} => {c.dst_name}.{c.dst_port}"
            )

        vhdl = _TOP_WRAPPER_TEMPLATE
        vhdl = vhdl.replace("${port_list}",           "\n".join(port_lines))
        vhdl = vhdl.replace("${component_decls}",     "\n".join(comp_decls))
        vhdl = vhdl.replace("${component_instances}", "\n".join(comp_insts))
        vhdl = vhdl.replace("${connections_vhdl}",    "\n".join(conn_lines))

        out = str(self.vhdl_dir / "top_wrapper.vhd")
        Path(out).write_text(vhdl, encoding="utf-8")
        return out

    # ── C++ wrapper генерація ──────────────
    def generate_cpp_wrapper(
        self, modules: list["ModuleSpec"], namespace: str = "spartan7_gen"
    ) -> str:
        """Генерує header-only C++ файл з константами оптимального маппінгу."""
        lines = [
            "// AUTO-GENERATED C++ wrapper — optimal module parameters",
            "#pragma once",
            f"namespace {namespace} {{",
        ]
        for m in modules:
            safe = re.sub(r"\W+", "_", m.name).upper()
            lines += [
                f"  // {m.kind.value} module: {m.name}",
                f"  constexpr int {safe}_WIDTH = {m.data_width};",
                f"  constexpr int {safe}_DEPTH = {m.depth};",
            ]
        lines += ["} // namespace"]

        out = str(self.work_dir / "generated_params.hpp")
        Path(out).write_text("\n".join(lines) + "\n", encoding="utf-8")
        log.info("Згенеровано C++ wrapper: %s", out)
        return out

    # ── Генерація команди прошивання ───────
    def generate_bitstream_cmd(
        self, device_id: str, bit_path: str, jtag: str = "auto"
    ) -> str:
        """Повертає рядок vivado команди для прошивання."""
        return (
            f"open_hw_manager\n"
            f"connect_hw_server\n"
            f"open_hw_target\n"
            f"set_property PROGRAM.FILE {{{bit_path}}} "
            f"[lindex [get_hw_devices] 0]\n"
            f"program_hw_devices [lindex [get_hw_devices] 0]\n"
            f"puts \"PROGRAM_DONE\"\n"
        )

    # ── Утиліти ────────────────────────────
    @staticmethod
    def _safe_name(name: str) -> str:
        """Перетворює ім'я на валідний VHDL ідентифікатор."""
        safe = re.sub(r"[^a-zA-Z0-9_]", "_", name)
        return safe if safe[0].isalpha() else "m_" + safe
